### ISSUE TITLE
would be nice to compare more than 2 LLM responses with ranking

### ISSUE THREAD

**Issue by Jack-Yu-815** [wgryc/phasellm#32]
Inside phasellm/eval.py, all the evaluators outputs a binary preference (either A or B). It would be nice to compare more than 2 LLM response at once, and let the evaluators output a ranking of all the given LLM responses.

One constraint is that the evaluator model has a max_token limit. Adding more LLM responses in the evaluator's user prompt may exceed that limit. But other than that, a ranking of different LLMs' responses will provide more insights and result in more efficient comparisons.

**Comment by wgryc** [comment]
Great idea, thanks for sharing it!

We'll have someone on our team explore this idea in the coming week or so.
