### ISSUE TITLE
Missing requirements in setup.py

### ISSUE THREAD

**Issue by radiac** [wgryc/phasellm#53]
0.0.12 introduces dependencies for `transformers`, `accelerate` and `torch`; they're in requirements.txt, but not setup.py

**Comment by wgryc** [comment]
Thanks! Working on a fix to have a phasellm[complete] package for those who want to run LLMs locally. The default phasellm install will support cloud-based LLMs.

**Comment by wgryc** [comment]
Our v0.0.14 release should address this. Let us know if it doesn't.
