### ISSUE TITLE
Anthropic error handling

### ISSUE THREAD

**Issue by mike-burns** [wgryc/phasellm#76]
The response from Anthropic is handled in two different ways:

https://github.com/wgryc/phasellm/blob/a6375d54279d711565e2b61323f652b494107d75/phasellm/llms.py#L1140-L1145

https://github.com/wgryc/phasellm/blob/a6375d54279d711565e2b61323f652b494107d75/phasellm/llms.py#L1288

In the first, if the response JSON does not match the expected structure, we get back the empty string. In the second, we get back a `KeyError`.

Ideally there'd be a way to know whether the Anthropic response was an error, such as a rate limit error. Currently that looks like either `''` or `KeyError`.

**Comment by mike-burns** [comment]
What about raising a PhaseLLM-specific error from `complete_chat`?

**Comment by skoczen** [comment]
Just clarifying here that this is a bug report on the library, not a feature request - please make your own choices on whether it's worth implementing or not - we'll work around and find a solution from our side!
